# Generated by Django 3.2.9 on 2021-11-12 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='Дата тренировки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
        migrations.CreateModel(
            name='SetDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='№ подхода')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('repeats', models.PositiveSmallIntegerField(default=0, verbose_name='Повторения')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.exercise', verbose_name='Подход №')),
            ],
            options={
                'verbose_name': 'Описание подхода',
                'verbose_name_plural': 'Описание подходов',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workout', verbose_name='Тренировка'),
        ),
    ]
