# Generated by Django 3.2.9 on 2021-11-14 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211112_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='sportsman_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Имя спортсмена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.workout', verbose_name='Тренировка'),
        ),
        migrations.AlterField(
            model_name='setdescription',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.exercise', verbose_name='Упражнение'),
        ),
    ]
